name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose other environments like 'windows-latest', 'macos-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (or 17)
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # or 17
          distribution: 'temurin'  # Using Temurin JDK distribution (replacing AdoptOpenJDK)

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies with Maven
        run: mvn clean install  # This will install the dependencies and build your project

      - name: Run Tests with TestNG
        run: mvn test  # Runs tests using Maven with TestNG

      - name: Upload TestNG Reports (updated to v3)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testng-reports
          path: target/test-classes/testng-results.xml  # Ensure this path is correct
