name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for Continuous Integration (CI)
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java environment using Temurin JDK
      - name: Set up JDK 11 with Temurin
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the version of JDK you want (e.g., '11', '17', etc.)
          distribution: 'temurin'  # Use the Temurin distribution

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies and run TestNG tests using Maven
      - name: Build and Run TestNG tests
        run: mvn clean install -DsuiteXmlFile=testng.xml

  # Job for Continuous Deployment (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy only if build is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production (adjust for your deployment method)
        run: |
          # Add your deployment commands here (for example, SSH deployment)
          ssh -i /path/to/private/key user@your-server "cd /path/to/project && git pull && mvn install && pm2 restart app"
