name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for Continuous Integration (CI)
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java environment (adjust to your Java version)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: ' adoptium '

      # Step 3: Install dependencies using Maven
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          maven-version: '3.6.3'

      # Step 4: Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Run TestNG tests using testng.xml
      - name: Run TestNG tests
        run: mvn test -DsuiteXmlFile=testng.xml

  # Job for Continuous Deployment (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy only if build is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production (adjust for your deployment method)
        run: |
          # Add your deployment com
